// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-RAJrwLwsnq6LpB1rye2j_XQ_UyDirS8',
    appId: '1:598734741715:web:90bd122811724ad8e97426',
    messagingSenderId: '598734741715',
    projectId: 'enviroment-9db04',
    authDomain: 'enviroment-9db04.firebaseapp.com',
    storageBucket: 'enviroment-9db04.firebasestorage.app',
    measurementId: 'G-C0JVBZNQS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoY9n0G4OkgqZXxh4RfHqvxqcOyQHbMQQ',
    appId: '1:598734741715:android:394da4514f309542e97426',
    messagingSenderId: '598734741715',
    projectId: 'enviroment-9db04',
    storageBucket: 'enviroment-9db04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKb7h6oyNfl4967mn_cCT7F1OupAlodnM',
    appId: '1:598734741715:ios:2c7dde73a031631ae97426',
    messagingSenderId: '598734741715',
    projectId: 'enviroment-9db04',
    storageBucket: 'enviroment-9db04.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKb7h6oyNfl4967mn_cCT7F1OupAlodnM',
    appId: '1:598734741715:ios:2c7dde73a031631ae97426',
    messagingSenderId: '598734741715',
    projectId: 'enviroment-9db04',
    storageBucket: 'enviroment-9db04.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-RAJrwLwsnq6LpB1rye2j_XQ_UyDirS8',
    appId: '1:598734741715:web:0be5f6c39d9e5624e97426',
    messagingSenderId: '598734741715',
    projectId: 'enviroment-9db04',
    authDomain: 'enviroment-9db04.firebaseapp.com',
    storageBucket: 'enviroment-9db04.firebasestorage.app',
    measurementId: 'G-PDJWCJ4XNY',
  );

}