import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure`

// 🧭 Screens
import 'screens/splash_screen.dart';
import 'screens/home_screen.dart';
import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/about_screen.dart';
import 'screens/contact_screen.dart';
import 'screens/footprint.dart';
import 'screens/waste_tracker_screen.dart';
import 'screens/eco_products_screen.dart';
import 'screens/challenges_screen.dart';
import 'screens/recipes_screen.dart';
import 'screens/gallery_screen.dart';
import 'screens/profile_screen.dart';
// ✅ NEWLY ADDED

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase before running the app
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: "Sustainable Living 🌱",
      theme: ThemeData(
        primaryColor: const Color(0xFF4CAF50),
        colorScheme: const ColorScheme.light(
          primary: Color(0xFF4CAF50),
          secondary: Color(0xFF81C784),
        ),
        scaffoldBackgroundColor: Color(0xFFF3F7F2),
        useMaterial3: true,
      ),

      // 🏁 Start from splash screen
      initialRoute: '/',

      // 📍 All routes registered here
      routes: {
        '/': (context) => const SplashScreen(),
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/home': (context) => const HomeScreen(),
        '/about': (context) => const AboutScreen(),
        '/contact': (context) => const ContactScreen(),
        '/carbon': (context) => const CarbonFootprintScreen(),
        '/waste': (context) => const WasteTrackerScreen(),
        '/products': (context) => const EcoProductsScreen(),
        '/Challange': (context) => const ChallengesScreen(),
        '/recipes': (context) => const RecipesScreen(),
        '/gallery': (context) => const GalleryScreen(),
        '/profile': (context) => const ProfileScreen(),
        // ✅ NEW ROUTE
      },
    );
  }
}
